### ISSUE TITLE
Tela de cadastro de usuários

### ISSUE THREAD

**Issue by MatheusBrandalise** [DEVinHouse-Clamed-V3/projeto-blog-pet-em-grupo-javascript#3]
Implemente a tela de criação de conta conforme a imagem em anexo.

- O campo de nome deve ser obrigatório.
- O campo de URL da foto deve conter uma URL válida.
- O campo de email deve conter um endereço de email válido.
- O campo de senha deve ter entre 8 e 16 caracteres.
- O campo de confirmação de senha deve corresponder exatamente à senha digitada.
- O campo de biografia não deve exceder 300 caracteres.

Ao submeter e validar o formulário, armazene o usuário criado no local storage no seguinte formato:

```JSON
{
"id": 123,
"nome": "",
"foto": "",
"email": "",
"senha": "",
"biografia": ""
}
```

Adicione um evento de "input" no campo de foto, de forma que, ao digitar a URL, seja exibido um preview da imagem conforme o design na imagem em anexo.

A tela deve ser responsiva, adaptando-se a diferentes tamanhos de dispositivos.

![image](https://github.com/user-attachments/assets/b15a08ab-12d6-4ce9-91f2-02df001974e8)

**Comment by MatheusBrandalise** [comment]
**ATUALIZAÇÃO DE PROGRESSO 01**
Feito estilização e validação dos campos.

![image](https://github.com/user-attachments/assets/4bf6354a-958a-4167-9662-4b23207cc5fa)

**ToDo**

- [x] Renderizar imagem quando informado o link no input;
- [x] Campo de senha deve ter entre 8 e 16 caracteres.
- [x] Campo de confirmação de senha deve corresponder exatamente à senha digitada.
- [x] Campo de biografia não deve exceder 300 caracteres;

**Comment by MatheusBrandalise** [comment]
**ATUALIZAÇÃO DE PROGRESSO 02**
Melhoria na validação de campos, preview de imagem ao digitar endereço no campo.

![image](https://github.com/user-attachments/assets/927d05c8-521d-49d9-a141-ffecd58091b9)


![image](https://github.com/user-attachments/assets/5f73fe23-7548-4863-ab52-05a9eb846b5f)
